# Generated by Django 3.2.8 on 2021-10-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscomments', '0002_comments_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
