# Generated by Django 3.2.8 on 2021-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscomments', '0004_auto_20211019_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='comment', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(help_text='ID', max_length=20, null=True),
        ),
    ]
